apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: udagram-feed
  name: udagram-feed
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: udagram-feed
    spec:
      containers:
      - image: dahluwalia3/dahluwalia-api-feed
        name: udagram-feed
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m" 
        env:
        - name: POSTGRES_USERNAME
          value: dahluwalia
        - name: POSTGRES_PASSWORD
          value: Devansh12
        - name: POSTGRES_HOST
          value: dockerproject.cmevnimkz1ew.us-east-2.rds.amazonaws.com
        - name: POSTGRES_DB
          value: postgres
        - name: AWS_BUCKET
          value: udacity-dahluwalia3-dev
        - name: AWS_REGION
          value: us-east-2
        - name: AWS_PROFILE
          value: default
        - name: JWT_SECRET
          value: hello
        - name: URL
          value: http://localhost:8100
      restartPolicy: Always


